<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net9.0</TargetFramework><RootNamespace>Jellyfin.Plugin.TrickplayComplete</RootNamespace><AssemblyName>Jellyfin.Plugin.TrickplayComplete</AssemblyName><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><GenerateAssemblyInfo>false</GenerateAssemblyInfo></PropertyGroup><ItemGroup><PackageReference Include="Jellyfin.Controller" Version="10.11.11"><ExcludeAssets>runtime</ExcludeAssets></PackageReference><PackageReference Include="Jellyfin.Model" Version="10.11.11"><ExcludeAssets>runtime</ExcludeAssets></PackageReference></ItemGroup><ItemGroup><EmbeddedResource Include="Web\configPage.html" /></ItemGroup></Project>