<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net8.0</TargetFramework><RootNamespace>Jellyfin.Plugin.TrickplayComplete</RootNamespace><AssemblyName>Jellyfin.Plugin.TrickplayComplete</AssemblyName><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><GenerateAssemblyInfo>false</GenerateAssemblyInfo></PropertyGroup><ItemGroup><PackageReference Include="Jellyfin.Controller" Version="10.11.11" /><PackageReference Include="Jellyfin.Model" Version="10.11.11" /><PackageReference Include="Jellyfin.Server.Implementations" Version="10.11.11" /></ItemGroup></Project>